language: android
#jdk: oraclejdk8
#sudo: false
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-28

    - extra-android-support
    - extra-android-m2repository
#    - sys-img-armeabi-v7a-android-28

  licenses:
      - 'android-sdk-license.*'
#      - android-sdk-license-.+

before_install:
  - chmod +x gradlew
#  - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
#  - mkdir "$ANDROID_HOME/licenses" || true
#  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# script: ./gradlew build
